[package]
name = "decryptor_s2"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
binrw = "0.15.0"
compression = "0.1.5"
crc32fast = "1.4.2"
encoding_rs = "0.8.35"
minstd = "0.9.4"
rayon = "1.10.0"
simple-eyre = "0.3.1"
walkdir = "2.5.0"
