[package]
name = "decrypter_S2"
version = "0.1.0"
edition = "2021"

[dependencies]
compression = "0.1.5"
encoding_rs = "0.8.35"
minstd = "0.9.4"
rayon = "1.10.0"
simple-eyre = "0.3.1"
walkdir = "2.5.0"
zerocopy = { version = "0.8.14", features = ["derive"] }
